export const CHANNELS = {
  appState: "skill-hub:app-state",
  backend: "skill-hub:backend",
  selectDirectory: "skill-hub:select-directory",
  openPath: "skill-hub:open-path",
  listSkillFiles: "skill-hub:list-skill-files",
  readSkillFile: "skill-hub:read-skill-file",
  writeSkillFile: "skill-hub:write-skill-file",
  deleteSkillFile: "skill-hub:delete-skill-file",
  scanSkillSafety: "skill-hub:scan-skill-safety",
  exportSkill: "skill-hub:export-skill",
  listRules: "skill-hub:list-rules",
  readRule: "skill-hub:read-rule",
  writeRule: "skill-hub:write-rule",
  createRule: "skill-hub:create-rule",
  deleteRule: "skill-hub:delete-rule",
  linkRule: "skill-hub:link-rule",
  unlinkRule: "skill-hub:unlink-rule",
  getCliRuleStatus: "skill-hub:get-cli-rule-status",
} as const;
